# Generated by Django 5.2.5 on 2025-08-15 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Theatre', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='performance',
            name='theatre_hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Theatre.theatrehall'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='performance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Theatre.performance'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Theatre.reservation'),
        ),
    ]
