# Generated by Django 5.2.5 on 2025-08-15 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Theatre', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='play',
            new_name='plays',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='play',
            new_name='plays',
        ),
    ]
