# Generated by Django 5.2.2 on 2025-08-25 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Theatre", "0005_alter_ticket_reservation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="actor",
            name="plays",
        ),
        migrations.RemoveField(
            model_name="genre",
            name="plays",
        ),
        migrations.AddField(
            model_name="play",
            name="actors",
            field=models.ManyToManyField(related_name="plays", to="Theatre.actor"),
        ),
        migrations.AddField(
            model_name="play",
            name="genres",
            field=models.ManyToManyField(related_name="plays", to="Theatre.genre"),
        ),
    ]
