# Generated by Django 5.2.2 on 2025-08-25 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Theatre", "0006_remove_actor_plays_remove_genre_plays_play_actors_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="performance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="Theatre.performance",
            ),
        ),
    ]
